# ______  _   _   _____   _   _   ______  _   _   _   _____   _   _       ___   _____  
#|___  / | | | | /  _  \ | | | | |___  / | | | | | | /  ___| | | | |     /   | /  _  \ 
#   / /  | |_| | | | | | | | | |    / /  | |_| | | | | |     | |_| |    / /| | | | | | 
#  / /   |  _  | | | | | | | | |   / /   |  _  | | | | |     |  _  |   / / | | | | | | 
# / /__  | | | | | |_| | | |_| |  / /__  | | | | | | | |___  | | | |  / /  | | | |_| | 
#/_____| |_| |_| \_____/ \_____/ /_____| |_| |_| |_| \_____| |_| |_| /_/   |_| \_____/ 
#
#ZHICHAO出品必属精品


#最后一个分号后面是要执行的指令，前几个分号都是简化指令，既可以在聊天框使用（大家都能看到），又可以/私人使用
commands:
  - 回家;h;H;home;home
  - 帮助;help
  - 回主城;回城;spawn;s;S;spawn
  - 回去;back;b;B;back
  - tpr;tpr
  - tps;tps
  - 菜单;menu;c;C;cd;CD;deluxemenu open basics_menu
  - 富豪榜;baltop;baltop
  - 我的现金;money;bal
  - 在此处安家;定居;sethome;sh;sethome
  - 我要签到;签到;signin gui
  - 来吧;来叭;tpaccept
  - 土地;res info
  - 自杀;suicide
  - 我的点卷;points me
  - c;deluxemenu open basics_menu
  - cd;deluxemenu open basics_menu
  - bid;ca gui bid

